### ISSUE TITLE
Install Caddy

### ISSUE THREAD

**Issue by vst** [telostat/teloshost#5]
For apt sources:

```yaml
apt:
  sources:
    caddy:
      source: deb [arch=amd64] https://dl.cloudsmith.io/public/caddy/stable/deb/ubuntu $RELEASE main
      keyid: 65760C51EDEA2017CEA2CA15155B6D79CA56EA34
```

For packages:

```yaml
packages:
  - "caddy"
```

Also, let's try to change or remove the default website entirely. Default Caddy welcome page is not a proper page for us.
